/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apkmahasiswa;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.DecimalFormat;
/**
 *
 * @author HP
 */
public class Admin extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form Admin
     */
    public Admin() {
        
        setIcon();
        initComponents();
        Koneksi.getKoneksi();  
        data();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        hiddenID.setVisible(false);
    }
    
    private void data(){
     try{
            con = Koneksi.getKoneksi();
            String sql1 = "SELECT * FROM mahasiswa order by id ASC";
            st = con.createStatement();
            rs = st.executeQuery(sql1);
            int no = 0;
            while(rs.next()){
                DefaultTableModel model = (DefaultTableModel) TableMahasiswa.getModel();
                Object[] row = new Object[10];
                row[0] = no = no + 1;
                row[1] = rs.getString("nama");
                row[2] = rs.getString("npm");
                row[3] = rs.getString("prodi");  
                row[4] = rs.getString("jurusan");  
                row[5] = rs.getString("kelas") + " - " + rs.getString("semester");
                double DPK1;
                DPK1 = Double.parseDouble(rs.getString("dpk"));
                String Sisa = Integer.toString(6000000 - rs.getInt("dpk"));
                double Sisa2 = Double.parseDouble(Sisa); 
                DecimalFormat DF = new DecimalFormat("#,###,###");        
                String DPK = DF.format(DPK1);
                String Sisa3 = DF.format(Sisa2);
                row[6] = DPK;
                row[7] = Sisa3;
                String status = "";
                if (Integer.parseInt(rs.getString("dpk")) == 6000000) {
                    status = "Lunas";
                }else {
                    status = "Belum Lunas";
                }
                row[8] = status;
                row[9] = rs.getInt("id");
                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNPM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputProdi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inputJurusan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputSemester = new javax.swing.JTextField();
        inputKelas = new javax.swing.JTextField();
        inputDPK = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMahasiswa = new javax.swing.JTable();
        hiddenID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tombol_profile = new javax.swing.JMenu();
        tombol_tabel = new javax.swing.JMenu();
        tombol_keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NPM                   :");

        inputNPM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputNPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNPMActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jurusan                :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelas       :");

        inputProdi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hukum", "Ekonomi", "Teknik", "FKIP", "FISIP", " " }));
        inputProdi.setSelectedIndex(-1);
        inputProdi.setToolTipText("");
        inputProdi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputProdiItemStateChanged(evt);
            }
        });
        inputProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProdiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Lengkap     :");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Semester  :");

        inputJurusan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJurusanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DPK        :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prodi                   :");

        inputSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSemesterActionPerformed(evt);
            }
        });

        inputKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKelasActionPerformed(evt);
            }
        });

        inputDPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDPKActionPerformed(evt);
            }
        });
        inputDPK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputDPKKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputDPKKeyTyped(evt);
            }
        });

        inputNama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnSimpan)
                        .addGap(28, 28, 28)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnHapus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inputSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(inputKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDPK))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16)
                    .addComponent(inputDPK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus))
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        TableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Lengkap", "NPM", "Prodi", "Jurusan", "Kelas/Semester", "DPK", "Sisa", "Status", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMahasiswa);
        if (TableMahasiswa.getColumnModel().getColumnCount() > 0) {
            TableMahasiswa.getColumnModel().getColumn(0).setResizable(false);
            TableMahasiswa.getColumnModel().getColumn(9).setMinWidth(0);
            TableMahasiswa.getColumnModel().getColumn(9).setPreferredWidth(0);
            TableMahasiswa.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        hiddenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(hiddenID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hiddenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 930, 380));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apkmahasiswa/background3.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        tombol_profile.setText("Profile");
        tombol_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_profileMouseClicked(evt);
            }
        });
        jMenu1.add(tombol_profile);

        tombol_tabel.setText("Tabel");
        tombol_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_tabelMouseClicked(evt);
            }
        });
        jMenu1.add(tombol_tabel);

        tombol_keluar.setText("Keluar");
        tombol_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_keluarMouseClicked(evt);
            }
        });
        jMenu1.add(tombol_keluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    }//GEN-LAST:event_jMenu1MouseClicked

    private void tombol_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_profileMouseClicked
        // TODO add your handling code here:
        new Profile().setVisible(true);
        dispose();
    }//GEN-LAST:event_tombol_profileMouseClicked

    private void tombol_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_tabelMouseClicked
        // TODO add your handling code here:
        new Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_tombol_tabelMouseClicked

    private void tombol_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_keluarMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_tombol_keluarMouseClicked

    private void hiddenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenIDActionPerformed

    private void TableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMahasiswaMouseClicked
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);

        int i = TableMahasiswa.getSelectedRow();
        TableModel model = TableMahasiswa.getModel();

        String kelasSemester = model.getValueAt(i, 5).toString();
        String noSpaceStr = kelasSemester.replaceAll("\\s", "");
        String[] kata = noSpaceStr.split("-");
        String kelas = kata[0];
        String jurusan = kata[1];

        inputNama.setText(model.getValueAt(i, 1).toString());
        inputNPM.setText(model.getValueAt(i, 2).toString());
        inputProdi.setSelectedItem(model.getValueAt(i, 3).toString());
        inputJurusan.setSelectedItem(model.getValueAt(i, 4).toString());
        inputKelas.setText(kelas);
        inputSemester.setText(jurusan);
        inputDPK.setText(model.getValueAt(i, 6).toString());
        hiddenID.setText(model.getValueAt(i, 9).toString());
    }//GEN-LAST:event_TableMahasiswaMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
            con = Koneksi.getKoneksi();

            String nilai_dpk = inputDPK.getText().replace(",", "");
            String sql = "DELETE FROM mahasiswa WHERE id='"+hiddenID.getText()+"'";
            st = con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
            this.dispose();
            ApkMahasiswa.oke();
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            con = Koneksi.getKoneksi();

            String nilai_dpk = inputDPK.getText().replace(",", "");
            String sql = "UPDATE mahasiswa set "
            + "nama='"+inputNama.getText()+"',"
            + "npm='"+inputNPM.getText()+"',"
            + "prodi='"+inputProdi.getSelectedItem()+"',"
            + "jurusan='"+inputJurusan.getSelectedItem()+"',"
            + "kelas='"+inputKelas.getText()+"',"
            + "semester='"+inputSemester.getText()+"',"
            + "dpk='"+nilai_dpk+"'"
            + "where id='"+hiddenID.getText()+"'";
            st = con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil diedit");
            this.dispose();
            ApkMahasiswa.oke();
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            con = Koneksi.getKoneksi();
            String nilai_dpk = inputDPK.getText().replace(",", "");
            String sql = "INSERT INTO mahasiswa (nama,npm,prodi,jurusan,kelas,semester,dpk) VALUES("
            + "'"+inputNama.getText()+"',"
            + "'"+inputNPM.getText()+"',"
            + "'"+inputProdi.getSelectedItem()+"',"
            + "'"+inputJurusan.getSelectedItem()+"',"
            + "'"+inputKelas.getText()+"',"
            + "'"+inputSemester.getText()+"',"
            + "'"+nilai_dpk+"')";
            st = con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan");
            this.dispose();
            ApkMahasiswa.oke();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputDPKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDPKKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDPKKeyTyped

    private void inputDPKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDPKKeyReleased
        if (inputDPK.getText().toString() != "") {
            String S_angka_normal = inputDPK.getText().replaceAll("\\,", "");
            double D_angka_Normal = Double.parseDouble(S_angka_normal);
            DecimalFormat DF = new DecimalFormat("#,###,###");
            inputDPK.setText(DF.format(D_angka_Normal));
        }
    }//GEN-LAST:event_inputDPKKeyReleased

    private void inputDPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDPKActionPerformed

    private void inputKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKelasActionPerformed

    private void inputSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSemesterActionPerformed

    private void inputJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJurusanActionPerformed

    }//GEN-LAST:event_inputJurusanActionPerformed

    private void inputProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProdiActionPerformed
        if(inputProdi.getSelectedItem().equals("Hukum")){
            inputJurusan.removeAllItems();
            inputJurusan.addItem("Ilmu Hukum S1");
        }else if(inputProdi.getSelectedItem().equals("Ekonomi")){
            inputJurusan.removeAllItems();
            inputJurusan.addItem("Manajemen S1");
            inputJurusan.addItem("Akuntansi S1");

        }else if(inputProdi.getSelectedItem().equals("Teknik")){
            inputJurusan.removeAllItems();
            inputJurusan.addItem("Teknik Informatika S1");
            inputJurusan.addItem("Teknik Sipil S1");
            inputJurusan.addItem("Teknik Elektro S1");
            inputJurusan.addItem("Teknik Industri S1");
            inputJurusan.addItem("Arsitektur S1");

        }else if(inputProdi.getSelectedItem().equals("FISIP")){
            inputJurusan.removeAllItems();
            inputJurusan.addItem("Ilmu Pemerintahan S1");
            inputJurusan.addItem("Ilmu Komunikasi S1");
            inputJurusan.addItem("Kesejahteraan Sosial S1");
            inputJurusan.addItem("Kepolisian D3");

        }else if(inputProdi.getSelectedItem().equals("FKIP")){
            inputJurusan.removeAllItems();
            inputJurusan.addItem("Pendidikan Ekonomi S1");
            inputJurusan.addItem("Pendidikan Matematika S1");
            inputJurusan.addItem("Pendidikan Guru SD S1");
        }
    }//GEN-LAST:event_inputProdiActionPerformed

    private void inputProdiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputProdiItemStateChanged

    }//GEN-LAST:event_inputProdiItemStateChanged

    private void inputNPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMahasiswa;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField hiddenID;
    private javax.swing.JTextField inputDPK;
    private javax.swing.JComboBox<String> inputJurusan;
    private javax.swing.JTextField inputKelas;
    private javax.swing.JTextField inputNPM;
    private javax.swing.JTextField inputNama;
    private javax.swing.JComboBox<String> inputProdi;
    private javax.swing.JTextField inputSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu tombol_keluar;
    private javax.swing.JMenu tombol_profile;
    private javax.swing.JMenu tombol_tabel;
    // End of variables declaration//GEN-END:variables

    //Membuat Icon logo aplikasi
    private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.png")));
    }
}
